### ISSUE TITLE
Official Documentation reads like a template

### ISSUE THREAD

**Issue by stain** [bioexcel/biobb_documentation#1]
https://biobb-documentation.readthedocs.io/en/latest/ is linked to from http://mmb.irbbarcelona.org/biobb/ as "Documentation -> Official Documentation"

However the actual content reads like a template, e.g.

https://biobb-documentation.readthedocs.io/en/latest/first_steps.html#installation says

> First off, please go to the biobb_template GitHub repository and install it in your computer as indicated in the README.md file in the repository:
> 
> https://github.com/bioexcel/biobb_template
> Download repository
> 
> Although the biobb_template repository is available at GitHub and thus you can clone it, we strongly recommend you to download it compressed and start your new project from scratch.

I would expect these pages to have a general introduction to BioBB like in <https://www.youtube.com/watch?v=I7ZxRBhYO3E> and <https://www.youtube.com/watch?v=ou1DOGNs0xM> and perhaps link to the individual modules and biobb_adapters.

**Comment by gbayarri** [comment]
Indeed, _Official documentation_ is not a good name for this link. What we will do is to change the name of this button to _Template documentation_ and add an _Official documentation_ button linking to:

 https://biobb.readthedocs.io/en/latest/readme.html

And in this README we will add a new section _About biobb_ with a description and the links to the videos and biobb_adapters.

Do you agree?

**Comment by gbayarri** [comment]
done
